routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::get('/', function () {
        return view('landingpage.index');
    });

    Route::get('/login', function () {
        return view('auth.login');
    });

    Route::get('/register', function () {
        return view('auth.register');
    });
});


// Route::resource('kategori', 'KategoriController');

// Route::resource('post', 'PostController');

// Route::resource('pertanyaan', 'PertanyaanController');


Route::middleware(['auth'])->group(function () {
    // KategoriController
    Route::get('/kategori/mycategory', 'KategoriController@mycategory');
    Route::resource('kategori', 'KategoriController');
    
    
    // PostController
    Route::get('/post/myquestion', 'PostController@myquestion');
    Route::resource('post', 'PostController');

    // Route::resource('pertanyaan', 'PertanyaanController');
    Route::resource('profile', 'ProfileController')->only('index', 'show', 'update');



    // Comment
    Route::resource('comment', 'CommentController');
    Route::post('/comment', 'CommentController@comment');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('kategori');

Route::post('upload', 'PostController@upload');

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="#">
      <img src="{{ asset('landingpage/img/logo/logov2.png') }}" alt="logo">
    </a>
    <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex" type="button" data-toggle="minimize">
      <span class="typcn typcn-th-menu"></span>
    </button>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle btn btn-sm h-25 d-flex justify-content-center align-items-center text-light" href="#" data-toggle="dropdown" id="plus" style="background-color: #06bbcc">
          <i class="mdi mdi-library-plus mr-0"></i>
          <h4 class="mb-0 ml-1">Create New</h4>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="plus">
          <a href="/kategori/create" class="dropdown-item">
          <i class="mdi mdi-puzzle" style="color: #06bbcc"></i>
          Create Category
          </a>
          <a href="/post/create" class="dropdown-item">
          <i class="mdi mdi-cloud-print" style="color: #06bbcc"></i>
          Create Question
          </a>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="typcn typcn-th-menu"></span>
    </button>
  </div>
</nav>

resources/views/layouts/partials/setting_panel.blade.php
<!-- partial:partials/_settings-panel.html -->
<div class="theme-setting-wrapper">
    <div id="settings-trigger" style="cursor: pointer; background: #06bbcc;"><i class="typcn typcn-cog-outline"></i></div>
    <div id="theme-settings" class="settings-panel">
      <i class="settings-close typcn typcn-delete-outline"></i>
      <p class="settings-heading">SIDEBAR SKINS</p>
      <div class="sidebar-bg-options" id="sidebar-light-theme">
        <div class="img-ss rounded-circle bg-light border mr-3"></div>
        Light
      </div>
      <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
        <div class="img-ss rounded-circle bg-dark border mr-3"></div>
        Dark
      </div>
      <p class="settings-heading mt-2">HEADER SKINS</p>
      <div class="color-tiles mx-0 px-4">
        <div class="tiles success"></div>
        <div class="tiles warning"></div>
        <div class="tiles danger"></div>
        <div class="tiles primary"></div>
        <div class="tiles info"></div>
        <div class="tiles dark"></div>
        <div class="tiles default border"></div>
      </div>
    </div>
</div>

resources/views/layouts/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <div class="d-flex sidebar-profile">
        <div class="sidebar-profile-image">
          @if (Auth::user()->profile->gambar == "defaultlogo.png")
          <img src="{{ asset('/defaultimageuser/defaultlogo.png') }}" alt="image">
          @else
            <img src="{{ asset('/imageuser/'. Auth::user()->profile->gambar) }}" alt="image">
          @endif
          <span class="sidebar-status-indicator"></span>
        </div>
        <div class="sidebar-profile-name">
          <p class="sidebar-name">
            {{ Auth::user()->name }}
          </p>
          <p class="sidebar-designation">
            Welcome
          </p>
        </div>
      </div>
      <p class="sidebar-menu-title">Dash menu</p>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/kategori">
        <i class="typcn typcn-device-desktop menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <i class="mdi mdi-puzzle menu-icon"></i>
        <span class="menu-title">Categories</span>
        <i class="typcn typcn-chevron-right menu-arrow"></i>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="/kategori/mycategory">My Category</a></li>
          <li class="nav-item"> <a class="nav-link" href="/kategori">All Category</a></li>
          <li class="nav-item"> <a class="nav-link" href="/kategori/create">Create Category</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
        <i class="mdi mdi-note-text menu-icon"></i>
        <span class="menu-title">Questions</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="form-elements">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link" href="/post/myquestion">My Question</a></li>
          <li class="nav-item"><a class="nav-link" href="/post">All Question</a></li>
          <li class="nav-item"><a class="nav-link" href="/post/create/">Create Question</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/profile">
        <i class="mdi mdi-human-greeting
        menu-icon"></i>
        <span class="menu-title">Profile</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ route('logout') }}"  onclick="event.preventDefault();
      document.getElementById('logout-form').submit();">
        <i class="mdi mdi-login-variant menu-icon"></i>
        <span class="menu-title">{{ __('Logout') }}</span>
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
    </form>
    </li>
</nav>

resources/views/layouts/partials/sidebarOld.blade.php
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav sidebar position-fixed">
      <li class="nav-item">
        <div class="d-flex sidebar-profile">
          <div class="sidebar-profile-image">
            @if (Auth::user()->profile->gambar == "defaultlogo.png")
              <img src="{{ asset('/defaultimageuser/defaultlogo.png') }}" alt="image">
            @else
              <img src="{{ asset('/imageuser/'. Auth::user()->profile->gambar) }}" alt="image">
            @endif
            <span class="sidebar-status-indicator"></span>
          </div>
          <div class="sidebar-profile-name">
            <p class="sidebar-name">
              {{ Auth::user()->name }}
            </p>
            <p class="sidebar-designation">
              Welcome
            </p>
          </div>
        </div>

        <p class="sidebar-menu-title">Dash menu</p>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-tachometer-alt"></i>
          <span class="menu-title">
            <h4 class="m-0">Dashboard</h4>
          </span>
        </a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" data-toggle="collapse" href="#kategori" aria-expanded="false" aria-controls="kategori">
          <i class="fas fa-layer-group"></i>
          <span class="menu-title">
            <h4 class="m-0">Categories</h4>
          </span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="kategori">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item">
              <a class="nav-link" href="/kategori/mycategory">My Category</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{{ route('kategori.index') }}">All Category</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{{ route('kategori.create') }}">Create Category</a>
            </li>
          </ul>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-toggle="collapse" href="#question" aria-expanded="false" aria-controls="question">
          <i class="fas fa-quote-right"></i>
          <span class="menu-title">
            <h4 class="m-0">Question</h4>
          </span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="question">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item">
              <a class="nav-link" href="/post/myquestion">My question</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('post.index') }}">All question</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{{ route('post.create') }}">Create question</a>
            </li>
          </ul>
        </div>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{{ route('profile.index') }}">
          <i class="fas fa-user-cog"></i>
          <span class="menu-title">
            <h4 class="m-0">Profile</h4>
          </span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ route('logout') }}"
        onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt"></i>
          <span class="menu-title">
            {{ __('Logout') }}
          </span>
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
      </li>

    </ul>
</nav>