routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::get('/', function () {
        return view('landingpage.index');
    });

    Route::get('/login', function () {
        return view('auth.login');
    });

    Route::get('/register', function () {
        return view('auth.register');
    });
});


// Route::resource('kategori', 'KategoriController');

// Route::resource('post', 'PostController');

// Route::resource('pertanyaan', 'PertanyaanController');


Route::middleware(['auth'])->group(function () {
    // KategoriController
    Route::get('/kategori/mycategory', 'KategoriController@mycategory');
    Route::resource('kategori', 'KategoriController');
    
    
    // PostController
    Route::get('/post/myquestion', 'PostController@myquestion');
    Route::resource('post', 'PostController');

    // Route::resource('pertanyaan', 'PertanyaanController');
    Route::resource('profile', 'ProfileController')->only('index', 'show', 'update');



    // Comment
    Route::resource('comment', 'CommentController');
    Route::post('/comment', 'CommentController@comment');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('kategori');

Route::post('upload', 'PostController@upload');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = "kategori";
    protected $guarded = ['id'];

    // public $timestamps = false;


    public function post()
    {
        return $this->hasOne('App\Post');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;


use App\Post;

use App\User;

use App\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;


class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $title = "Category List";
        $kategori = Kategori::all();
        return view('kategori.index', compact('kategori', 'title'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Create Category";
        return view('kategori.create', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => ['required', 'unique:kategori'],
        ]);

        $kategori = new Kategori;
        $kategori->nama = $request->nama;
        $kategori->deskripsi = $request->deskripsi;
        $kategori->user_id = Auth::id();

        $kategori->save();

        return redirect('/kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategori = Kategori::find($id);
        $title = "Question List";
        $post = Post::where('kategori_id', $id)->get();
        return view('post.kategoripost', compact('kategori', 'post', 'title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Edit Category";
        $kategori = Kategori::findorfail($id);
        return view('kategori.edit', compact('kategori', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => ['required'],
        ]);

        $kategori = Kategori::findorfail($id);
        $kategori->nama = $request->nama;
        $kategori->deskripsi = $request->deskripsi;

        $kategori->update();
        return redirect('/kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::findorfail($id);
        $kategori->delete();
        return redirect('/kategori');
    }

    // Create Personal Controller
    public function mycategory()
    {
        $title = 'My Category';
        $kategori = Kategori::where('user_id', Auth::id())->get();
        return view('kategori.mycategory', compact('kategori', 'title'));
    }
}

resources/views/kategori/create.blade.php
@extends('layouts.master')

@section('menu-table')
    Categories
@endsection

@section('menu-form')
    Question
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-8 m-auto">
            <form action="/kategori" method="post">
                @csrf
                <div class="card" style="border-radius: 15px;">
                    <div class="card-header" style="border-radius: 15px 15px 0 0;background-color: #06bbcc;">
                        <h2 class="mb-0 text-light text-center">Create data category</h2>
                    </div>
                    <div class="card-body">

                        <div class="mb-3">
                            <label for="nama" class="form-label">
                                <h4 class="mb-0">Category Name</h4>
                            </label>
                            <input type="text" name="nama" class="form-control" id="nama">
                        </div>

                        @error('nama')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror

                        <div class="mb-3">
                            <label for="deskripsi" class="form-label">
                                <h4 class="mb-0">Description</h4>
                            </label>
                            <textarea name="deskripsi" class="form-control" id="deskripsi" rows="3"></textarea>
                        </div>

                        @error('deskripsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror

                        <button type="submit" class="btn btn-block" style="background-color: #06bbcc">
                            <h3 class="mb-0 text-light">Create</h3>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.master')

@section('menu-table')
    Categories
@endsection

@section('menu-form')
    Question
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-8 m-auto">
            <form action="/kategori/{{ $kategori->id }}" method="post">
                @csrf
                @method('put')
                <div class="card" style="border-radius: 15px;">
                    <div class="card-header bg-primary" style="border-radius: 15px 15px 0 0;">
                        <h2 class="mb-0 text-light text-center">Edit data category</h2>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="nama" class="form-label">
                                <h4 class="mb-0">Category Name</h4>
                            </label>
                            <input type="text" name="nama" class="form-control" id="nama" value="{{ $kategori->nama }}">
                        </div>

                        @error('nama')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror

                        <div class="mb-3">
                            <label for="deskripsi" class="form-label">
                                <h4 class="mb-0">Description</h4>
                            </label>
                            <textarea name="deskripsi" class="form-control" id="deskripsi" rows="3">{{ $kategori->deskripsi }}</textarea>
                        </div>

                        @error('deskripsi')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror

                        <button type="submit" class="btn btn-primary btn-block">
                            <h3 class="mb-0">Update</h3>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/kategori/index.blade.php
@extends('kategori.masterkategori')

@section('content')
<div class="card">
    <div class="card-header" style="background-color: #06bbcc">
        <h3 class="mb-0 text-light pt-2 pb-2">Category List</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered text-center">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Category name</th>
                    <th>Description</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $i = 1;
                @endphp
                @foreach ($kategori as $item)
                <tr>
                    <td>{{ $i }}</td>
                    <td>
                        <a href="/kategori/{{ $item->id }}">{{ $item->nama }}</a>
                    </td>
                    <td>{!! Str::limit($item->deskripsi, 50, $end='...') !!}</td>
                    {{-- <td>{{ $item->deskripsi }}</td> --}}
                    <td>
                        {{ $item->created_at }}
                    </td>
                    <td>
                        {{ $item->updated_at }}
                    </td>
                </tr>
                @php
                    $i++;
                @endphp
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
@endsection
@push('scripts')
<script src="{{ asset('themes/AdminLTE/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('themes/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script>

    $(function () {
        $("#example1").DataTable();
    });

    $('.show_confirm').click(function(event) {
          var form =  $(this).closest("form");
          var name = $(this).data("name");
          event.preventDefault();
          swal({
              title: `Are you sure you want to delete this question?`,
              text: "If you delete this, it will be gone forever.",
              icon: "warning",
              buttons: true,
              dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });
</script>
@endpush

resources/views/kategori/masterkategori.blade.php
@extends('layouts.master')

@section('menu-table')
    Categories
@endsection

@section('menu-form')
    Question
@endsection

@section('content')
@yield('button-back')
    <div class="card">
        <div class="card-header bg-primary">
            <h3 class="mb-0 text-light pt-2 pb-2">@yield('title-view-category')</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered text-center">
                <thead>
                    @yield('thead')
                </thead>
                <tbody>
                    @yield('tbody')
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

@push('scripts')

<script src="{{ asset('themes/adminLTE/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('themes/adminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>
    $(function () {
        $("#example1").DataTable();
    });
</script>
@endpush

resources/views/kategori/mycategory.blade.php
@extends('layouts.master')

@section('content')
    <div class="card">
        <div class="card-header" style="background-color: #06bbcc">
            <h3 class="mb-0 text-light pt-2 pb-2">My Category List</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Category name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i = 1;
                    @endphp
                    @foreach ($kategori as $item)
                    <tr>
                        <td>{{ $i }}</td>
                        <td>
                            <a href="/kategori/{{ $item->id }}">{{ $item->nama }}</a>
                        </td>
                        <td>{!! Str::limit($item->deskripsi, 50, $end='...') !!}</td>
                        {{-- <td>{{ $item->deskripsi }}</td> --}}
                        <td>
                            <a href="{{ route('kategori.edit', $item->id) }}" class="btn btn-info btn-sm btn-block mb-1">Edit</a>

                            <form action="{{ route('kategori.destroy', $item->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="show_confirm btn btn-danger btn-sm mb-1 btn-block text-light" data-toggle="tooltip" title='Delete'>Delete</button>
                            </form>
                        </td>
                    </tr>
                    @php
                        $i++;
                    @endphp
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

@push('scripts')

<script src="{{ asset('themes/AdminLTE/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('themes/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script>


    $(function () {
        $("#example1").DataTable();
    });

    $('.show_confirm').click(function(event) {
          var form =  $(this).closest("form");
          var name = $(this).data("name");
          event.preventDefault();
          swal({
              title: `Are you sure you want to delete this question?`,
              text: "If you delete this, it will be gone forever.",
              icon: "warning",
              buttons: true,
              dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });


</script>
@endpush